import{a as h,S as v,i as w}from"./assets/vendor-c493984e.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const L="43884583-1aaf199fc122235264ed6db18",E="https://pixabay.com/api/",P=async(e,s,i)=>{const o=new URLSearchParams({key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:i,page:s}),t=await h.get(`${E}?${o}`);if(t.status!=200)throw Error(t.statusText);return t.data},b=e=>e.map(s=>`<li>
        <div class='preview'>
            <a href='${s.largeImageURL}'><img src='${s.webformatURL}' alt="${s.tags}"/></a>
            <div class="stats">
                <div><span class='stat-title'>Likes</span><span>${s.likes}</span></div>
                <div><span class='stat-title'>Views</span><span>${s.views}</span></div>
                <div><span class='stat-title'>Comments</span><span>${s.comments}</span></div>
                <div><span class='stat-title'>Downloads</span><span>${s.downloads}</span></div>
            </div>
        </div>
  </li>`).join(""),y=(e,s)=>{e.style.display=s||"block"},m=e=>{e.style.display="none"},I=document.getElementById("search-form"),B=document.getElementById("search-input"),l=document.getElementById("results"),p=document.getElementById("loading-indicator"),u=document.getElementById("load-more"),f=15;let a=1,d="";const $=new v(".gallery a",{});function n(e){w.show({message:e,position:"topRight",timeout:2e3,color:"red"})}async function g(){if(d===""){n("Please, enter the search query!");return}y(p);try{const e=await P(d,a,f);if(console.log(e),e.total===0){n("Sorry, there are no images matching your search query. Please try again!");return}l.innerHTML=l.innerHTML+b(e.hits),$.refresh(),a*f>=e.totalHits&&(n("We're sorry, but you've reached the end of search results."),m(u))}catch{n("Sorry, some error occured. Please, try again!")}m(p)}I.addEventListener("submit",async e=>{e.preventDefault(),a=1,d=B.value.trim(),l.innerHTML="",await g(),y(u,"inline-block")});u.addEventListener("click",async e=>{a++,await g();let s=document.querySelector("#results li").getBoundingClientRect();console.log(s),setTimeout(()=>window.scrollBy({top:s.height*2,left:0,behavior:"smooth"}),300)});
//# sourceMappingURL=commonHelpers.js.map
