import{a as h,S as v,i as w}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))o(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function i(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(s){if(s.ep)return;s.ep=!0;const r=i(s);fetch(s.href,r)}})();const L="43884583-1aaf199fc122235264ed6db18",b="https://pixabay.com/api/",P=async(e,t,i)=>{const o=new URLSearchParams({key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:i,page:t});return(await h.get(`${b}?${o}`)).data},E=e=>e.map(t=>`<li>
        <div class='preview'>
            <a href='${t.largeImageURL}'><img src='${t.webformatURL}' alt="${t.tags}"/></a>
            <div class="stats">
                <div><span class='stat-title'>Likes</span><span>${t.likes}</span></div>
                <div><span class='stat-title'>Views</span><span>${t.views}</span></div>
                <div><span class='stat-title'>Comments</span><span>${t.comments}</span></div>
                <div><span class='stat-title'>Downloads</span><span>${t.downloads}</span></div>
            </div>
        </div>
  </li>`).join(""),p=(e,t)=>{e.style.display=t||"block"},l=e=>{e.style.display="none"},I=document.getElementById("search-form"),B=document.getElementById("search-input"),y=document.getElementById("results"),d=document.getElementById("loading-indicator"),u=document.getElementById("load-more"),f=15;let a=1,m="";const $=new v(".gallery a",{});function n(e){w.show({message:e,position:"topRight",timeout:2e3,color:"red"})}async function g(){p(d),l(u);try{const e=await P(m,a,f);if(console.log(e),e.total===0){l(d),n("Sorry, there are no images matching your search query. Please try again!");return}y.insertAdjacentHTML("beforeend",E(e.hits)),$.refresh(),a*f>=e.totalHits?n("We're sorry, but you've reached the end of search results."):p(u,"inline-block")}catch{n("Sorry, some error occured. Please, try again!")}l(d)}I.addEventListener("submit",async e=>{if(e.preventDefault(),a=1,m=B.value.trim(),y.innerHTML="",m===""){n("Please, enter the search query!");return}await g()});u.addEventListener("click",async e=>{a++,await g();let t=document.querySelector("#results li").getBoundingClientRect();console.log(t),setTimeout(()=>window.scrollBy({top:t.height*2,left:0,behavior:"smooth"}),300)});
//# sourceMappingURL=commonHelpers.js.map
